export { default as AboutUs } from './AboutUs'
export { default as Auth } from './Auth'
export { default as CreateSurvey } from './CreateSurvey'
export { default as MySurveys } from './MySurveys'
export { default as Profile } from './Profile'
export { default as ResultOfSurvey } from './ResultOfSurvey'
export { default as Survey } from './Survey'
export { default as Surveys } from './Surveys'